# Analyze Ole Jacob's Time Series Data

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
import netCDF4 as nc

# Dataset Overview

In [102]:
ds = nc.Dataset("../data/time_series/swd_flaate_popmod_3_many.nc")
ds

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format NETCDF3):
    Conventions: CF-1.5
    title: Current data from SINMOD
    institution: SINTEF Fisheries and Aquaculture
    grid_mapping: grid_mapping
    grid_mapping_name: polar_stereographic
    straight_vertical_longitude_from_pole: 58.0
    horizontal_resolution: 20000.0
    coordinate_north_pole: [ 174.   120.5]
    latitude_of_projection_origin: 90.0
    standard_parallel: 60.0
    barotropic_timestep: 21.4285714286
    baroclinic_timestep: 600.0
    _FillValue: -32768
    setup: swd_1d
    relax_e: T
    nested: T
    tidal_input: F
    DHA: 2.0
    smagorin: T
    biharmonic: F
    KBi: 8e+09
    COLDSTART: F
    ATMODATA: 0
    CM: 1.0
    CM2D: 1.0
    CH: 0.3
    CI: 5.0
    icedyn: T
    tidal_components: [0 0 0 0 0 0 0 0 0 0 0]
    dimensions(sizes): xc(100), yc(1), zc(1), time(128), dummySampleDim(6)
    variables(dimensions): int32 time(time,dummySampleDim), int32 grid_mapping(), floa

# Dimensions

In [94]:
ds.variables['xc']

<class 'netCDF4._netCDF4.Variable'>
float32 xc(xc)
    units: meter
    standard_name: projection_x_coordinate
    _CoordinateAxisType: GeoX
unlimited dimensions: 
current shape = (100,)
filling off

In [95]:
ds.variables['xc'][:]

array([   20000.,    40000.,    60000.,    80000.,   100000.,   120000.,
         140000.,   160000.,   180000.,   200000.,   220000.,   240000.,
         260000.,   280000.,   300000.,   320000.,   340000.,   360000.,
         380000.,   400000.,   420000.,   440000.,   460000.,   480000.,
         500000.,   520000.,   540000.,   560000.,   580000.,   600000.,
         620000.,   640000.,   660000.,   680000.,   700000.,   720000.,
         740000.,   760000.,   780000.,   800000.,   820000.,   840000.,
         860000.,   880000.,   900000.,   920000.,   940000.,   960000.,
         980000.,  1000000.,  1020000.,  1040000.,  1060000.,  1080000.,
        1100000.,  1120000.,  1140000.,  1160000.,  1180000.,  1200000.,
        1220000.,  1240000.,  1260000.,  1280000.,  1300000.,  1320000.,
        1340000.,  1360000.,  1380000.,  1400000.,  1420000.,  1440000.,
        1460000.,  1480000.,  1500000.,  1520000.,  1540000.,  1560000.,
        1580000.,  1600000.,  1620000.,  1640000., 

In [96]:
ds.variables['yc']

<class 'netCDF4._netCDF4.Variable'>
float32 yc(yc)
    units: meter
    standard_name: projection_y_coordinate
    _CoordinateAxisType: GeoY
unlimited dimensions: 
current shape = (1,)
filling off

In [98]:
ds.variables['yc'][:]

array([ 20000.], dtype=float32)

In [99]:
ds.variables['zc']

<class 'netCDF4._netCDF4.Variable'>
float32 zc(zc)
    units: m
    positive: down
    standard_name: depth
    _CoordinateAxisType: Height
unlimited dimensions: 
current shape = (1,)
filling off

In [100]:
ds.variables['zc'][:]

array([ 3.], dtype=float32)

# Variable List

In [103]:
print("Variables:\n")
for k in ds.variables.keys():
    print(k)

Variables:

time
grid_mapping
LayerDepths
xc
yc
zc
depth
Individual frond area
Ind int frond area
Number of individuals
Ind fresh weight
Ind dry weight
Nitrogen content
Carbon content
Carbon reserve
Nitrogen reserve
Struct w area
Stipe biomass
NO3 conc
NH4 conc
Temp
PAR
Current speed


# Load Variables

In [47]:
t = ds.variables['time']
ind = ds.variables['Number of individuals']
a = ds.variables['Individual frond area']
a1 = ds.variables['Ind int frond area']
xc = ds.variables['xc']
yc = ds.variables['yc']
zc = ds.variables['zc']

# Experiment

In [69]:
ds.variables['Temp'][:]

array([[[  4.72711849,   4.72711849,   4.72711849, ...,   4.72711849,
           4.72711849,   4.72711849]],

       [[  6.64391041,   6.64391041,   6.64391041, ...,   6.64391041,
           6.64391041,   6.64391041]],

       [[  6.68681908,   6.68681908,   6.68681908, ...,   6.68681908,
           6.68681908,   6.68681908]],

       ..., 
       [[ 10.77164459,  10.77164459,  10.77164459, ...,  10.77164459,
          10.77164459,  10.77164459]],

       [[ 10.75865936,  10.75865936,  10.75865936, ...,  10.75865936,
          10.75865936,  10.75865936]],

       [[ 10.63106155,  10.63106155,  10.63106155, ...,  10.63106155,
          10.63106155,  10.63106155]]], dtype=float32)

In [57]:
ds.variables['LayerDepths'][:]

array([ 3.], dtype=float32)

In [67]:
ds.variables['Ind fresh weight'][:]

array([[[  6.10351562e-03,   6.10351562e-03,   1.83105469e-02, ...,
           1.22070312e-02,   2.44140625e-02,   1.83105469e-02]],

       [[  1.22070312e-02,   1.22070312e-02,   2.44140625e-02, ...,
           1.83105469e-02,   3.66210938e-02,   3.05175781e-02]],

       [[  1.83105469e-02,   2.44140625e-02,   3.66210938e-02, ...,
           2.44140625e-02,   6.10351562e-02,   4.88281250e-02]],

       ..., 
       [[  1.97027435e+01,   3.93566742e+01,   4.75112152e+01, ...,
           6.36677094e+01,   1.51799011e+01,   2.40302734e+01]],

       [[  2.01422119e+01,   4.03759918e+01,   4.86770172e+01, ...,
           6.52668915e+01,   1.54789886e+01,   2.45735016e+01]],

       [[  2.06854401e+01,   4.16028290e+01,   5.00625610e+01, ...,
           6.71101990e+01,   1.58513184e+01,   2.52388000e+01]]], dtype=float32)

In [63]:
ds.variables['depth'][:]

array([[ -3.27680000e+04,  -3.27680000e+04,  -3.27680000e+04,
         -3.27680000e+04,   2.72000000e+02,  -3.27680000e+04,
         -3.27680000e+04,  -3.27680000e+04,  -3.27680000e+04,
          0.00000000e+00,   4.00000000e+08,   4.00000000e+08,
          4.00000000e+08,   4.00000000e+08,   4.00000000e+08,
          4.00000000e+08,   4.00000000e+08,   4.00000000e+08,
          4.00000000e+08,   0.00000000e+00,   2.00000000e+04,
          2.00000000e+04,   2.00000000e+04,   2.00000000e+04,
          2.00000000e+04,   2.00000000e+04,   2.00000000e+04,
          2.00000000e+04,   2.00000000e+04,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
        

In [61]:
ds.variables['PAR'][:].shape

(128, 1, 100)

In [60]:
yc[:]

array([ 20000.], dtype=float32)

In [107]:
ls ..

basic_shading_model/  COPYING   hdf5/     notes/    README    slides/
bin/                  cpp/      include/  outline/  reports/  timeline/
callgrind/            data/     julia/    plots/    results/
commands.txt          fortran/  Makefile  python/   scripts/


In [108]:
import os

In [104]:
ls

 3d_test.pickle                 kelp_shading-gradlab.ipynb*
 3d_test.py                     kelp_shading.ipynb
'Angle Diff Grid.ipynb'         kelp_volume.py
'Angular Grid Analysis.ipynb'   kelp_widgets.py
 attenuation.py                 keyboard.py
'Candy Corn.ipynb'              ks.py
 col.txt                        kv.py
 create_movie.py                light1/
 data.txt                       light2/
 exp_fit_test.py                light_data.py
 fit_movie.py                   mat.png
 fort.1                        'Memory Requirements.ipynb'
 fort.2                         mkdir/
 fort.3                         movie.sh*
 fort.4                         odecd2.py
 fort.7                         pqt_volume.py
 fort.8                         __pycache__/
 fortran_wrappers/              pyrad_in.txt
 frad_in.txt                    pyrad_out.txt
 frad_out.txt                   radiance2d.py
 frond_configuration.py         Redistribution.ipynb
'Frond Transformation.ipynb'    rhs.txt
 grid

In [59]:
xc[:]

array([   20000.,    40000.,    60000.,    80000.,   100000.,   120000.,
         140000.,   160000.,   180000.,   200000.,   220000.,   240000.,
         260000.,   280000.,   300000.,   320000.,   340000.,   360000.,
         380000.,   400000.,   420000.,   440000.,   460000.,   480000.,
         500000.,   520000.,   540000.,   560000.,   580000.,   600000.,
         620000.,   640000.,   660000.,   680000.,   700000.,   720000.,
         740000.,   760000.,   780000.,   800000.,   820000.,   840000.,
         860000.,   880000.,   900000.,   920000.,   940000.,   960000.,
         980000.,  1000000.,  1020000.,  1040000.,  1060000.,  1080000.,
        1100000.,  1120000.,  1140000.,  1160000.,  1180000.,  1200000.,
        1220000.,  1240000.,  1260000.,  1280000.,  1300000.,  1320000.,
        1340000.,  1360000.,  1380000.,  1400000.,  1420000.,  1440000.,
        1460000.,  1480000.,  1500000.,  1520000.,  1540000.,  1560000.,
        1580000.,  1600000.,  1620000.,  1640000., 

In [55]:
ds.variables['Current speed'][:]

array([[[ 0.07312238,  0.07312238,  0.07312238, ...,  0.07312238,
          0.07312238,  0.07312238]],

       [[ 0.07019258,  0.07019258,  0.07019258, ...,  0.07019258,
          0.07019258,  0.07019258]],

       [[ 0.02056944,  0.02056944,  0.02056944, ...,  0.02056944,
          0.02056944,  0.02056944]],

       ..., 
       [[ 0.22022152,  0.22022152,  0.22022152, ...,  0.22022152,
          0.22022152,  0.22022152]],

       [[ 0.20410776,  0.20410776,  0.20410776, ...,  0.20410776,
          0.20410776,  0.20410776]],

       [[ 0.13275552,  0.13275552,  0.13275552, ...,  0.13275552,
          0.13275552,  0.13275552]]], dtype=float32)

In [52]:
zc[:]

array([ 3.], dtype=float32)

In [40]:
t[:].shape

(128, 6)

In [37]:
a1[:].shape

(128, 1, 100)

In [41]:
a[:].shape

(128, 1, 100)

In [46]:
a1[:]

array([[[  0.        ,   0.        ,   0.        , ...,   0.        ,
           0.        ,   0.        ]],

       [[  0.        ,   0.        ,   0.        , ...,   0.        ,
           0.        ,   0.        ]],

       [[  0.        ,   0.        ,   0.        , ...,   0.        ,
           0.        ,   0.        ]],

       ..., 
       [[  2.71005249,   6.45465088,   7.94702148, ...,  11.97546387,
           1.840271  ,   3.33261108]],

       [[  2.7741394 ,   6.61947632,   8.13012695, ...,  12.26843262,
           1.86773682,   3.40585327]],

       [[  2.84738159,   6.82089233,   8.36816406, ...,  12.61636353,
           1.91351318,   3.49743652]]], dtype=float32)